### ISSUE TITLE
Maven dependencies Error while compiling

### ISSUE THREAD

**Issue by xraynt8** [MadMarty/madsonic-server-5.0#1]
I get the following error while trying to compile Build 3480:
Failed to execute goal on project madsonic-main: Could not resolve dependencies for project net.sourceforge.subsonic:madsonic-main:war:5.0: Failed to collect dependencies at net.sourceforge.subsonic:madsonic-lastfm-java:jar:5.0: Failed to read artifact descriptor for net.sourceforge.subsonic:madsonic-lastfm-java:jar:5.0: Failure to find net.sourceforge.subsonic:madsonic:pom:5.0 in http://repository.springsource.com/maven/bundles/release was cached in the local repository, resolution will not be reattempted until the update interval of com.springsource.repository.bundles.release has elapsed or updates are forced -> [Help 1]
How can i fix this?

**Comment by MadMarty** [comment]
to build from scratch use:

mvn clean install -P full
